import { Doctor } from "./types";

export const DOCTORS: Doctor[] = [
  { id: '1', name: 'Dr. Rahul Sharma', specialty: 'General Physician', image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80', about: 'Experienced general physician specializing in family medicine, chronic disease management, and primary healthcare across India.', isFree: true, gender: 'male' },
  { id: '13', name: 'Dr. Anjali Gupta', specialty: 'Cardiology', image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=400&q=80', about: 'Senior cardiologist with expertise in managing heart health, hypertension, and preventive cardiovascular care for the Indian lifestyle.', gender: 'female' },
  { id: '2', name: 'Dr. Priyanka Reddy', specialty: 'Neurologist', image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80', about: 'Expert in neurological disorders, specializing in migraine management, epilepsy, and neuro-rehabilitation services.', gender: 'female' },
  { id: '3', name: 'Dr. Amit Verma', specialty: 'Pediatrician', image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80', about: 'Dedicated child specialist providing comprehensive care from neonatal health to adolescent growth and immunizations.', gender: 'male' },
  { id: '4', name: 'Dr. Sunita Kulkarni', specialty: 'Dermatologist', image: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=400&q=80', about: 'Specializes in Indian skin types, treating acne, pigmentation, and various climatic effect-related skin conditions.', gender: 'female' },
  { id: '5', name: 'Dr. Vikram Singh', specialty: 'Orthopedic', image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80', about: 'Expert in bone and joint health, specializing in knee replacements, sports injuries, and posture-related issues.', gender: 'male' },
  { id: '6', name: 'Dr. Meera Saxena', specialty: 'Oncologist', image: 'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?auto=format&fit=crop&w=400&q=80', about: 'Compassionate medical oncologist providing evidence-based treatment plans and personalized cancer care.', gender: 'female' },
  { id: '7', name: 'Dr. Siddarth Malhotra', specialty: 'Psychiatrist', image: 'https://images.unsplash.com/photo-1576091160550-2173599211d0?auto=format&fit=crop&w=400&q=80', about: 'Specializes in mental wellness, addressing anxiety, depression, and stress management in high-pressure environments.', gender: 'male' },
  { id: '9', name: 'Dr. Rajesh Khanna', specialty: 'Gastroenterology', image: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=400&q=80', about: 'Expert in digestive health, managing IBS, acidity, and fatty liver conditions common in the Indian population.', gender: 'male' },
  { id: '10', name: 'Dr. Kavita Rao', specialty: 'Gynecology', image: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=400&q=80', about: 'Specialist in women’s reproductive health, prenatal care, and postnatal support for modern Indian women.', gender: 'female' },
  { id: '11', name: 'Dr. Arun Vijay', specialty: 'Otolaryngology', image: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&w=400&q=80', about: 'ENT specialist treating sinus, allergy issues, and hearing disorders with a focus on pollution-related respiratory health.', gender: 'male' },
  { id: '12', name: 'Dr. Shweta Singh', specialty: 'Psychologist', image: 'https://images.unsplash.com/photo-1612349317130-76ea46e01a85?auto=format&fit=crop&w=400&q=80', about: 'Focuses on behavioral therapy, counseling, and marital support with a deep understanding of Indian cultural dynamics.', gender: 'female' }
];
